[project]
name = "SaltSimulator"
version = "0.1.0"
description = "SaltSimulator-pixi"
authors = ["nieboer <roeland.nieboer@deltares.nl>"]
channels = ["gimli","conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tasks]
start = "python -m pip install --no-deps --editable ."
electric = 'jupyter notebook ./notebooks/Electrical_Resistivity_Tomography.ipynb'
acoustic = 'jupyter notebook ./notebooks/Acoutic_Tomography.ipynb'


[dependencies]
pygimli = ">=1.5.0,<1.6"
numpy = ">=1.26.4,<1.27"
ipykernel = ">=6.29.3,<6.30"
pandas = ">=2.2.2,<2.3"
jupyter = ">=1.0.0,<1.1"
matplotlib = ">=3.8.4,<3.9"
