[project]
name = "SaltSimulator"
version = "0.1.0"
description = "Add a short description here"
authors = ["nieboer <roeland.nieboer@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
